# Dev config override config.yaml
redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:}
  db: ${REDIS_DB:0}
kafka:
  bootstrap:
    servers: ${KAFKA_HOST:localhost:9092}
  group:
    id: ${KAFKA_GROUP_ID:preprocessing_group}
  auto:
    offset:
      reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
celery:
  broker: ${CELERY_BROKER_URL:redis://redis:6379/0}
  backend: ${CELERY_RESULT_BACKEND:redis://redis:6379/0}
storage:
  root_dir: ${STORAGE_ROOT_DIR:/tmp/fx-repo/preprocessing-service}
fx_storage:
  username: ${FX_STORAGE_USER:user}
  password: ${FX_STORAGE_PASS:user}
  host: ${FX_STORAGE_HOST:localhost}
  port: ${FX_STORAGE_PORT:9055}
  ssl: ${FX_STORAGE_SSL:false}
