version: "3.8"
services:
  fx-storage:
    build:
      dockerfile: "dockerfile"
      context: "storage"
    environment:
      # S3 config
      # local dev keys
      - S3_ACCESS_KEY=5MfxOFuj0zKwlLnd5sJ8
      - S3_SECRET_KEY=BUMmJxjMn2mFMw8YkZkK9lS2Zj73Vqd3vD3UQAkT
      - S3_ENDPOINT=fx-minio-container:9000
      - S3_SSL=false
      # Username and password used to authenticate every request
      - USERNAME=user
      - PASSWORD=user
      # Gin mode
      - GIN_MODE=debug
    ports:
      - "9055:8080"
    networks:
      - kafka-network
      - minio-network
    volumes:
      - "./storage:/usr/src/app"
  fx-minio:
    image: minio/minio
    container_name: fx-minio-container
    command: server --console-address ":9001" /data
    ports:
      -  "9000:9000"
      -  "9001:9001"
    volumes:
      - minio-data-volume:/data
    networks:
      - minio-network
  fx-zookeeper:
    image: ubuntu/zookeeper
    container_name: fx-zk-container
    networks:
      - zookeeper-network
    ports:
      - ":2181"
  fx-apache_kafka:
    image: ubuntu/kafka
    networks:
      - zookeeper-network
      - kafka-network
    environment:
      - ZOOKEEPER_HOST=fx-zk-container
      - ZOOKEEPER_PORT=2181
    ports:
      - ":9092"
    depends_on:
      - fx-zookeeper
  fx-redis:
    # For dev we are using only one redis instance
    image: redis:7-alpine
    ports:
      -  "6379:6379"
    networks:
      redis-network:

volumes:
  minio-data-volume:
networks:
  zookeeper-network:
  kafka-network:
  minio-network:
  redis-network: